---
title: "brms heritability aten larv"
author: "Alex Macadam"
date: "2024-01-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(brms)
library(tidyverse)
set.seed(123)
```

```{r}
setwd("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data")
```

```{r}
theme_Publication <- function(base_size=14, base_family="arial") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

#############################
Larvae
```{r}
Data<-as.data.frame(read.table(file= "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/aten_larv_survival_heritability.txt",header=TRUE))
Data$animal<-as.factor(Data$animal)
Data$culture<-as.factor(Data$culture)
Data$mother<-as.factor(Data$mother)
Data$father<-as.factor(Data$father)
head(Data)

#Data <- as.data.frame(Data)
```

```{r}
Ped<-as.data.frame(read.table(file= "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/aten_larv_ped.txt",header=TRUE))
for(x in 1:3) Ped[,x]<-as.factor(Ped[,x])
head(Ped)

#Ped = data.frame(Ped)
```

```{r}
Amat <- as.matrix(nadiv::makeA(Ped))
```

```{r}
#brms_m1.1_larv <- brm(
#  survival ~ 1 + (1 | gr(animal, cov = Amat)),
#  data = Data,
#  data2 = list(Amat = Amat),
#  family = gaussian(),
#  chains = 3, cores = 3, iter = 15000000, warmup = 150000, thin = 1500,
#  control = list(adapt_delta = 0.9999, max_treedepth = 20),
#  refresh = 100
#)

#save(brms_m1.1_larv, file = "brms_m1.1_larv.rda")
```

```{r}
load("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/brms_m1.1_larv.rda")
plot(brms_m1.1_larv)
```

```{r}
mcmc_plot(brms_m1.1_larv, type = "acf")
```

```{r}
summary(brms_m1.1_larv)
```

```{r}
v_animal <- (VarCorr(brms_m1.1_larv, summary = FALSE)$animal$sd)^2
v_r <- (VarCorr(brms_m1.1_larv, summary = FALSE)$residual$sd)^2
h.bwt.1_larv <- as.mcmc(v_animal / (v_animal + v_r))
summary(h.bwt.1_larv)
```

```{r}
plot(h.bwt.1_larv)
```

```{r}
Var.table <- as_draws_df(brms_m1.1_larv)
Var.table$h.bwt.1_larv <- as.mcmc((Var.table$sd_animal__Intercept)^2 / ((Var.table$sd_animal__Intercept)^2 + (Var.table$sigma)^2))
summary(Var.table$h.bwt.1_larv)
plot(Var.table$h.bwt.1_larv)
```

```{r}
h.bwt.2_larv<- as.data.frame(h.bwt.1_larv)
h.bwt.2_larv<- rownames_to_column(h.bwt.2_larv, var = "MCMC") |> dplyr::rename(Heritability = Intercept) |>
  dplyr::mutate(MCMC = as.integer(MCMC))
```

OR
```{r}
# or
Var.table <- as_draws_df(brms_m1.1_larv)
Var.table$h.bwt.1_larv <- as.mcmc((Var.table$sd_animal__Intercept)^2 / ((Var.table$sd_animal__Intercept)^2 + (Var.table$sigma)^2))
summary(Var.table$h.bwt.1_larv)
```

```{r}
plot(Var.table$h.bwt.1_larv)
```

```{r}
brms_her_line<- h.bwt.2_larv|>
  ggplot() +
  geom_line(aes(x=MCMC, y=Heritability)) +
  geom_hline(yintercept = 0.91462, color = "red") +
  theme_Publication() +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        )
brms_her_line

brms_her_dens<- h.bwt.2_larv|>
  ggplot() +
  geom_density(aes(Heritability)) +
  theme_Publication() +
  labs(y="Density") +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        )
brms_her_dens
```

bayesR heritability
```{r}
#average heritability = 0.905284551
h2<- read.table("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/bayesr_simout.frq.txt", header = TRUE)

#h2_sum <- summarySE(h2, measurevar="Heritability",
#                     groupvars=c("Method"), na.rm=TRUE)

bayesr_her_line<- h2|>
  ggplot() +
  geom_line(aes(x=MCMC, y=Heritability)) +
  geom_hline(yintercept = 0.905, color = "red") +
  theme_Publication() +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        )

bayesr_her_dens<- h2|>
  ggplot() +
  geom_density(aes(Heritability)) +
  theme_Publication() +
  labs(y="Density") +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        )
bayesr_her_dens
```

Join BRMS and BayesR
```{r}
h.bwt.2_larv<- h.bwt.2_larv |>
  mutate(Method = "BRMS_larv")

h2<- h2 |>
  mutate(Method = "BayesR")

heritability_larv<- rbind(h.bwt.2_larv, h2)

her_plot_larv<- heritability_larv |>
  ggplot() +
  geom_density(aes(Heritability, fill = Method), alpha = 0.8) +
  geom_vline(aes(xintercept = 0.905284551), colour = "#386cb0", size = 1, linetype="dashed") +
  geom_vline(aes(xintercept = 0.91462), colour = "#fdb462", size = 1, linetype="dashed") +
  theme_Publication() +
  labs(y="Density") +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        ) +
    scale_fill_Publication()
her_plot_larv
```

##################
juveniles

```{r}
Data<-as.data.frame(read.table(file= "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/aten_juv_survival.txt",header=TRUE))
Data$animal<-as.factor(Data$animal)
Data$culture<-as.factor(Data$culture)
Data$mother<-as.factor(Data$mother)
Data$father<-as.factor(Data$father)
head(Data)

#Data <- as.data.frame(Data)
```

```{r}
Ped<-as.data.frame(read.table(file= "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/aten_juv_ped.txt",header=TRUE))
for(x in 1:3) Ped[,x]<-as.factor(Ped[,x])
head(Ped)

#Ped = data.frame(Ped)
```

```{r}
Amat <- as.matrix(nadiv::makeA(Ped))
#write.csv(Amat, "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Amat_juveniles.csv")
#Amat<- read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Amat_juveniles.csv", row.names = 1) |> data.matrix()
```

```{r}
#brms_m1.1_juv <- brm(
#  survival ~ 1 + (1 | gr(animal, cov = Amat)),
#  data = Data,
#  data2 = list(Amat = Amat),
#  family = gaussian(),
#  chains = 3, cores = 3, iter = 15000000, warmup = 150000, thin = 1500,
#  control = list(adapt_delta = 0.9999, max_treedepth = 20),
#  refresh = 100
#)

#save(brms_m1.1, file = "/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/brms_m1_juv_4.rda")
```

```{r}
load("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/brms_m1_juv_4.rda")
plot(brms_m1.1_juv)
```

```{r}
mcmc_plot(brms_m1.1_juv, type = "acf")
```

```{r}
summary(brms_m1.1_juv)
```

```{r}
v_animal <- (VarCorr(brms_m1.1_juv, summary = FALSE)$animal$sd)^2
v_r <- (VarCorr(brms_m1.1_juv, summary = FALSE)$residual$sd)^2
h.bwt.1_juv <- as.mcmc(v_animal / (v_animal + v_r))
summary(h.bwt.1_juv)
```

```{r}
plot(h.bwt.1_juv)
```

```{r}
h.bwt.2_juv<- as.data.frame(h.bwt.1_juv)
h.bwt.2_juv<- rownames_to_column(h.bwt.2_juv, var = "MCMC") |> dplyr::rename(Heritability = Intercept) |>
  dplyr::mutate(MCMC = as.integer(MCMC))
```

OR
```{r}
# or
Var.table <- as_draws_df(brms_m1.1_juv)
Var.table$h.bwt.1_juv <- as.mcmc((Var.table$sd_animal__Intercept)^2 / ((Var.table$sd_animal__Intercept)^2 + (Var.table$sigma)^2))
summary(Var.table$h.bwt.1_juv)
```

```{r}
plot(Var.table$h.bwt.1_juv)
```

```{r}
h.bwt.2_juv<- h.bwt.2_juv |>
  mutate(Method = "BRMS_juv")

heritability_all<- rbind(heritability_larv, h.bwt.2_juv) |>
  mutate(Method = factor(Method), levels = c("BayesR","BRMS_juv","BRMS_larv"))

her_plot_larv<- heritability_all |>
  ggplot() +
  geom_density(aes(Heritability, fill = Method), alpha = 0.8) +
  geom_vline(aes(xintercept = 0.889959), colour = "#386cb0", size = 1, linetype="dashed") +
  geom_vline(aes(xintercept = 0.91462), colour = "#7fc97f", size = 1, linetype="dashed") +
  geom_vline(aes(xintercept = 0.661388), colour = "#fdb462", size = 1, linetype="dashed") +
  theme_Publication() +
  labs(y="Density") +
  theme(plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
        ) +
  scale_fill_Publication()
her_plot_larv
```
