---
title: "Untitled"
output: html_document
date: "2025-01-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
# load sig SNPs from corr analysis
cor<- read.csv("/Users/alexmacadam/Documents/GitHub/AGF-DArT/data/cor_sig_SNP_names.csv", header = T)
cor<- as.vector(cor$x)
# load sig SNPs from fisher test
fisher<- read.csv("/Users/alexmacadam/Documents/GitHub/AGF-DArT/data/fisher_sig_SNP_names.csv", header = T)
fisher<- as.vector(fisher$x)

in_both <- intersect(cor, fisher)
```

```{r}
#create a list object of significant genes 
sig_SNP_list<- list(Correlation=cor, 
                 Fisher_test=fisher
                 )

library(ggvenn)
af_venn<- ggvenn(
  sig_SNP_list,
  fill_color = c("#0073C2FF", "#CD534CFF")
  #stroke_size = 0.5, set_name_size = 4
  )
af_venn
```


Map
```{r}
# Chromosome length info
lengths <- read_tsv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/ragtag.scaffold_lengths.txt", col_names = c("chr","length"),show_col_types = FALSE)

#load chromosome offsets
offsets <- lengths %>% arrange(dplyr::desc(length)) %>% 
  dplyr::mutate(offset=cumsum(length)-length) %>% 
  dplyr::mutate(scaffold_num = row_number())

axis_chr<- offsets %>% 
  mutate(centre=offset+length/2) %>% 
  mutate(chr_id=ifelse(grepl(chr,pattern="chr"),chr,"Unplaced")) %>% 
  mutate(chr_id=str_remove(chr_id,"_RagTag"),chr_id=str_remove(chr_id,"chr")) %>% 
  group_by(chr_id) %>% 
  dplyr::summarise(centre = mean(centre))
```

```{r}
mh_data_corr <- read_table("/Users/alexmacadam/Documents/GitHub/AGF-DArT/data/ci.ragtag.txt",col_names = c("chr","pos","SNP2","SNP","chr_orig","pos_orig")) %>% 
  left_join(offsets) %>%
  mutate(abs_pos = pos + offset) %>%
  mutate(chr_type=ifelse(scaffold_num %% 2 == 0,"dark", "light")) %>% 
  mutate(chr_type=ifelse(grepl(chr,pattern="chr"),chr_type,"unplaced"))

mh_data_corr<- left_join(mh_data_corr, ci, by = "SNP")
```

```{r}

```

