---
title: "Untitled"
output: html_document
date: "2024-08-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries
library(tidyverse)
library(stringr)
library(wesanderson)
library(GGally)
library(gridExtra)
library(reshape2)
library(cartography)  # for custom palette
library(cowplot)  # for nuanced multipanel plots of asymmetrical panels
library(ggrepel)  # repelling plot labels
library(ggpubr)
library(ggthemes)
set.seed(123)
```

```{r}
surv_larv_reef<-read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Larvae_reef.csv")
surv_juv_reef<-read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Juvenile_reef_SC.csv")
surv_juv<- read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Juvenile_family.csv")
surv_larv<- read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Larvae_family.csv") |> filter(type == "individual")
fams<- read.table("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/families.txt")
```

```{r}
#https://rpubs.com/Koundy/71792
theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

```{r}
pd <- position_dodge(width=0.2)
pal <- wes_palette("Zissou1", 5, type = "discrete")
scalesize <- function(x) sprintf("%.1f", x)
```

Larvae reef crosses plot
```{r}
#plot survival all
surv_larv_plot<- surv_larv_reef |> filter(Timepoint == "2") |> filter(type == "individuals") |>
  ggplot(aes(x=reorder(popcross, desc(mean)), y=mean))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, alpha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(0,100), breaks=seq(0,100,20))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("Ambient" = 0.4, "Hot" = 1)) +
  #facet_wrap(~Treatment) +
  scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_larv_plot
```

All larvae families plot
```{r, warning = FALSE}
# Filter the data for Temp == 'hot' to use these means for reordering the x-axis
hot_means <- surv_larv |>
  filter(Temp == 'Hot' & Timepoint == "2") |>
  group_by(Culture) |>
  dplyr::summarize(mean_hot = mean)

cultures <- surv_larv |>
  filter(Temp == 'Hot' & Timepoint == "2" & type == "individual") |>
  dplyr::select(Culture)

# Merge the 'hot_means' with the original data
surv_larv <- surv_larv |> dplyr::left_join(hot_means, by = "Culture")

#plot survival all
surv_larv<- surv_larv |> filter(Timepoint == "2") |> filter(type == "individual") |> filter(mean != "NA")
surv_larv_plot_all<- surv_larv |>
  ggplot(aes(x=reorder(Culture, desc(mean_hot)), y=mean, alpha = Temp))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, apha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(0,100), breaks=seq(0,100,20))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("Ambient" = 0.4, "Hot" = 1)) +
  #facet_wrap(~Treatment) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_larv_plot_all
```

Sequenced larvae families plot
```{r, warning = FALSE}
#plot survival
surv_larv2<- surv_larv |> filter(Culture %in% fams$V1)
surv_seq_larv_plot<- surv_larv2 |>
  ggplot(aes(x=reorder(Culture, desc(mean_hot)), y=mean))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, alpha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(0,100), breaks=seq(0,100,20))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("Ambient" = 0.4, "Hot" = 1)) +
  #facet_wrap(~Treatment) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_seq_larv_plot
```

Juveniles reef crosses plot
```{r, warning = FALSE}
# Filter the data for Temp == 'hot' to use these means for reordering the x-axis
juv_hot_reef_means <- surv_juv_reef |>
  filter(Temp == 'HOT') |>
  group_by(Reefcross) |>
  dplyr::summarize(mean_hot = mean)

juv_reef <- surv_juv_reef |>
  filter(Temp == 'HOT') |>
  dplyr::select(Reefcross) |>
  mutate(Reefcross = as.factor(Reefcross))

#juv_hot_means <- cbind(juv_reef, juv_hot_reef_means)

# Merge the 'hot_means' with the original data
surv_juv_reef <- surv_juv_reef |>
  left_join(juv_hot_reef_means, by = "Reefcross")

#plot survival
surv_juv_plot<- surv_juv_reef |>
  ggplot(aes(x=reorder(Reefcross, desc(mean_hot)), y=mean, colour=region, alpha = Temp))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, alpha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(50,100), breaks=seq(50,100,10))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("AMB" = 0.4, "HOT" = 1)) +
  #facet_wrap(~Treatment, nrow = 3) +
  scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_juv_plot
```

```{r}
# Filter the data for Temp == 'hot' to use these means for reordering the x-axis
juv_hot_means <- surv_juv |>
  filter(Temp == 'HOT') |>
  group_by(Family) |>
  dplyr::summarize(mean_hot = mean)

juv_cultures <- surv_juv |>
  filter(Temp == 'HOT') |>
  dplyr::select(Family)

#juv_hot_means <- cbind(juv_cultures, juv_hot_means)

# Merge the 'hot_means' with the original data
surv_juv <- surv_juv |>
  left_join(juv_hot_means, by = "Family")

#plot survival
surv_juv_plot_all<- surv_juv |>
  ggplot(aes(x=reorder(Family, desc(mean_hot)), y=mean, colour=Temp))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, alpha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(50,100), breaks=seq(50,100,10))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("AMB" = 0.4, "HOT" = 1)) +
  #facet_wrap(~Treatment, nrow = 3) +
  scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_juv_plot_all
```

```{r}
#plot survival
surv_seq_juv_plot<- surv_juv |> filter(Family %in% fams$V1) |>
  ggplot(aes(x=reorder(Family, desc(mean_hot)), y=mean, colour=Temp))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
#  geom_hline(yintercept=0, color='black', size = 0.5)+
  geom_pointrange(aes(ymin=mean-se, ymax=mean+se, color=region, alpha = Temp), position=position_dodge(width=0.5))+
#  geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  scale_y_continuous(limits=c(50,100), breaks=seq(50,100,10))+
  scale_color_manual(values=pal[c(1,3,5)]) +
  scale_alpha_manual(values = c("AMB" = 0.4, "HOT" = 1)) +
  #facet_wrap(~Treatment, nrow = 3) +
  scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )
surv_seq_juv_plot
```

```{r, warning=FALSE}
library(patchwork)

plot<- surv_larv_plot + surv_seq_larv_plot + surv_juv_plot + surv_seq_juv_plot + plot_layout(ncol = 2, guides = 'collect', widths = c(1, 2))  + plot_annotation(tag_levels = 'A')
plot

plot<- surv_seq_larv_plot + surv_seq_juv_plot + plot_layout(ncol = 2, guides = 'collect')  + plot_annotation(tag_levels = 'A')
plot
```

Larvae survival contributions from parents
```{r}
# Load necessary libraries
library(dplyr)

# Step 1: Load the data
data <- read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Larvae_family.csv")

#Step 2: Filter data for 'Temp = hot', 'Timepoint = 2', and 'type = individual'
filtered_data <- data %>%
  filter(Temp == 'Hot' & Timepoint == 2 & type == 'individual')

#Step 3: Calculate overall mean survival and SE for the filtered data
overall_mean <- mean(filtered_data$mean, na.rm = TRUE)
overall_se <- mean(filtered_data$se, na.rm = TRUE)

#Step 4: Calculate the survival deviance and SE deviance for both mom and dad roles
filtered_data <- filtered_data %>%
  mutate(
    survival_deviance = (mean - overall_mean) / overall_mean,
    se_deviance = (se - overall_se) / overall_se
  )

#Step 5: Calculate the overall survival deviance and SE deviance for each parent
#Group by Mom and Dad, and take the average deviance for each parent
mothers_data <- filtered_data %>%
  group_by(Mom) %>%
  summarize(
    overall_survival_deviance_mom = mean(survival_deviance, na.rm = TRUE),
    overall_se_deviance_mom = mean(se_deviance, na.rm = TRUE)
  )

fathers_data <- filtered_data %>%
  group_by(Dad) %>%
  summarize(
    overall_survival_deviance_dad = mean(survival_deviance, na.rm = TRUE),
    overall_se_deviance_dad = mean(se_deviance, na.rm = TRUE)
  )

#Step 6: Merge the mother's and father's data into one dataframe
final_data <- full_join(mothers_data, fathers_data, by = c("Mom" = "Dad"))

#Step 7: Rename the 'Mom' column to 'Parent' to indicate these are hermaphroditic individuals
final_data <- final_data %>%
  rename(Parent = Mom)

#Step 8: Calculate an overall deviance for each parent, combining their roles as both mom and dad
final_data <- final_data %>%
  mutate(
    overall_survival_deviance = rowMeans(cbind(overall_survival_deviance_mom, overall_survival_deviance_dad)),
    overall_se_deviance = rowMeans(cbind(overall_se_deviance_mom, overall_se_deviance_dad))
  )

#Step 9: Add the 'Region' column based on the conditions in 'Parent'
final_data <- final_data %>%
  mutate(
    Region = case_when(
      grepl("^Davies[0-9]+|^Palms[0-9]+", Parent) ~ "Central",  # Match 'Davies' or 'Palms' followed by numbers
      grepl("^Jewell|^Parke|^Switzer", Parent) ~ "North",       # Match 'Jewell', 'Parke', or 'Switzer'
      TRUE ~ NA_character_  # Assign NA if none of the conditions match
    )
  )

#Step 10: Calculate northern mean survival and SE for the filtered data
north <- final_data |> dplyr::filter(Region == "North") |> na.omit()
north_mean<- mean(north$overall_survival_deviance)
north_se <- mean(north$overall_se_deviance, na.rm = TRUE)

#Step 11: Calculate central mean survival and SE for the filtered data
central <- final_data |> dplyr::filter(Region == "Central") |> na.omit()
central_mean<- mean(central$overall_survival_deviance)
central_se <- mean(central$overall_se_deviance, na.rm = TRUE)

moms<- final_data |> 
  dplyr::select(Parent, Region, overall_survival_deviance_mom, overall_se_deviance_mom) |>
  na.omit()

#Step 12: Plot mum survival deviances

mom_plot<- moms |>
  ggplot(aes(x=reorder(Parent, desc(overall_survival_deviance_mom)), y=overall_survival_deviance_mom, colour=Region))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
  #geom_hline(aes(yintercept=north_mean),color='red', size = 0.5)+
  #geom_hline(aes(yintercept=central_mean), color='blue', size = 0.5)+
  geom_hline(aes(yintercept=0), color='black', size = 0.6)+
  geom_pointrange(aes(ymin=overall_survival_deviance_mom-overall_se_deviance_mom, ymax=overall_survival_deviance_mom+overall_se_deviance_mom, color=Region), position=position_dodge(width=0.8)) +
  #geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  #scale_y_continuous(limits=c(-1.5,1.25), breaks=seq(-1.5,1.25,0.5), labels = scalesize)+
  scale_color_manual(values=pal[c(1,5)]) +
  #facet_wrap(~Parent.1, ncol = 3) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )

dads<- final_data |> 
  dplyr::select(Parent, Region, overall_survival_deviance_dad, overall_se_deviance_dad) |>
  na.omit()

#Step 13: Plot dad survival deviances

dad_plot<- dads |>
  ggplot(aes(x=reorder(Parent, desc(overall_survival_deviance_dad)), y=overall_survival_deviance_dad, colour=Region))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
  #geom_hline(aes(yintercept=north_mean),color='red', size = 0.5)+
  #geom_hline(aes(yintercept=central_mean), color='blue', size = 0.5)+
  geom_hline(aes(yintercept=0), color='black', size = 0.6)+
  geom_pointrange(aes(ymin=overall_survival_deviance_dad-overall_se_deviance_dad, ymax=overall_survival_deviance_dad+overall_se_deviance_dad, color=Region), position=position_dodge(width=0.8)) +
  #geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  #scale_y_continuous(limits=c(-1.5,1.25), breaks=seq(-1.5,1.25,0.5), labels = scalesize)+
  scale_color_manual(values=pal[c(1,5)]) +
  #facet_wrap(~Parent.1, ncol = 3) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )

deviance_plot<- mom_plot + dad_plot + plot_layout(guides = 'collect') + plot_annotation(tag_levels = 'A')
```

Juvenile survival contributions from parents
```{r}
# Load necessary libraries
library(dplyr)

#Step 1: Load the data
data <- read.csv("/Users/alexmacadam/Dropbox/PhD/Chapter3_Genomics/Final analysis/Data/Yr1_Aten_Juvenile_family.csv")

#Step 2: Filter data for 'Temp = hot', 'Timepoint = 2', and 'type = individual'
filtered_data <- data %>%
  filter(Temp == 'HOT')

#Step 3: Calculate overall mean survival and SE for the filtered data
overall_mean <- mean(filtered_data$mean, na.rm = TRUE)
overall_se <- mean(filtered_data$se, na.rm = TRUE)

#Step 4: Calculate the survival deviance and SE deviance for both mom and dad roles
filtered_data <- filtered_data %>%
  mutate(
    survival_deviance = (mean - overall_mean) / overall_mean,
    se_deviance = (se - overall_se) / overall_se
  )

#Step 5: Calculate the overall survival deviance and SE deviance for each parent
#Group by Mom and Dad, and take the average deviance for each parent
mothers_data <- filtered_data %>%
  group_by(Mom) %>%
  dplyr::summarize(
    overall_survival_deviance_mom = mean(survival_deviance, na.rm = TRUE),
    overall_se_deviance_mom = mean(se_deviance, na.rm = TRUE)
  )

fathers_data <- filtered_data %>%
  group_by(Dad) %>%
  dplyr::summarize(
    overall_survival_deviance_dad = mean(survival_deviance, na.rm = TRUE),
    overall_se_deviance_dad = mean(se_deviance, na.rm = TRUE)
  )

#Step 6: Merge the mother's and father's data into one dataframe
final_data <- full_join(mothers_data, fathers_data, by = c("Mom" = "Dad"))

#Step 7: Rename the 'Mom' column to 'Parent' to indicate these are hermaphroditic individuals
final_data <- final_data %>%
  dplyr::rename(Parent = Mom)

#Step 8: Calculate an overall deviance for each parent, combining their roles as both mom and dad
final_data <- final_data %>%
  mutate(
    overall_survival_deviance = rowMeans(cbind(overall_survival_deviance_mom, overall_survival_deviance_dad)),
    overall_se_deviance = rowMeans(cbind(overall_se_deviance_mom, overall_se_deviance_dad))
  )

#Step 9: Add the 'Region' column based on the conditions in 'Parent'
final_data <- final_data %>%
  mutate(
    Region = case_when(
      grepl("^Davies[0-9]+|^Palms[0-9]+", Parent) ~ "Central",  # Match 'Davies' or 'Palms' followed by numbers
      grepl("^Jewell|^Parke|^Switzer", Parent) ~ "North",       # Match 'Jewell', 'Parke', or 'Switzer'
      TRUE ~ NA_character_  # Assign NA if none of the conditions match
    )
  )

#Step10: Calculate northern mean survival and SE for the filtered data
north <- final_data |> dplyr::filter(Region == "North") |> na.omit()
north_mean<- mean(north$overall_survival_deviance)
north_se <- mean(north$overall_se_deviance, na.rm = TRUE)

#Step11: Calculate central mean survival and SE for the filtered data
central <- final_data |> dplyr::filter(Region == "Central") |> na.omit()
central_mean<- mean(central$overall_survival_deviance)
central_se <- mean(central$overall_se_deviance, na.rm = TRUE)

moms<- final_data |> 
  dplyr::select(Parent, Region, overall_survival_deviance_mom, overall_se_deviance_mom) |>
  na.omit()

#Step 12: Plot mum survival deviances
mom_plot<- moms |>
  ggplot(aes(x=reorder(Parent, desc(overall_survival_deviance_mom)), y=overall_survival_deviance_mom, colour=Region))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
  #geom_hline(aes(yintercept=north_mean),color='red', size = 0.5)+
  #geom_hline(aes(yintercept=central_mean), color='blue', size = 0.5)+
  geom_hline(aes(yintercept=0), color='black', size = 0.6)+
  geom_pointrange(aes(ymin=overall_survival_deviance_mom-overall_se_deviance_mom, ymax=overall_survival_deviance_mom+overall_se_deviance_mom, color=Region), position=position_dodge(width=0.8)) +
  #geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  #scale_y_continuous(limits=c(-1.5,1.25), breaks=seq(-1.5,1.25,0.5), labels = scalesize)+
  scale_color_manual(values=pal[c(1,5)]) +
  #facet_wrap(~Parent.1, ncol = 3) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )

dads<- final_data |> 
  dplyr::select(Parent, Region, overall_survival_deviance_dad, overall_se_deviance_dad) |>
  na.omit()

#Step 13: Plot dad survival deviances
dad_plot<- dads |>
  ggplot(aes(x=reorder(Parent, desc(overall_survival_deviance_dad)), y=overall_survival_deviance_dad, colour=Region))+
  #geom_hline(yintercept=filter(survival_combined, Population.location=="Central x Central")$mean, color='gray', lty='dashed')+
  #geom_hline(aes(yintercept=north_mean),color='red', size = 0.5)+
  #geom_hline(aes(yintercept=central_mean), color='blue', size = 0.5)+
  geom_hline(aes(yintercept=0), color='black', size = 0.6)+
  geom_pointrange(aes(ymin=overall_survival_deviance_dad-overall_se_deviance_dad, ymax=overall_survival_deviance_dad+overall_se_deviance_dad, color=Region), position=position_dodge(width=0.8)) +
  #geom_text(aes(label=crosstype2, y=-0.5), size=3, fontface = "bold", angle=90, position=position_dodge(width=0.8), vjust=0.5, hjust=1) +
  #scale_y_continuous(limits=c(-1.5,1.25), breaks=seq(-1.5,1.25,0.5), labels = scalesize)+
  scale_color_manual(values=pal[c(1,5)]) +
  #facet_wrap(~Parent.1, ncol = 3) +
  #scale_shape_manual(values=c(15, 19, 17, 18)) +
  labs(x='Family', y="Survival (%)")+
  theme_Publication() +
  theme(legend.key.height = unit(0.3, "cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        plot.margin = margin(rep(0.5,4)),
        legend.position="right",
        legend.direction = "vertical",
        axis.text.x = element_text(angle = 90),
        axis.text.y = element_text(angle = 90)
        )

deviance_plot<- mom_plot + dad_plot + plot_layout(guides = 'collect') + plot_annotation(tag_levels = 'A')
deviance_plot
```
